### ISSUE TITLE
Statusbar error at login

### ISSUE THREAD

**Issue by ZethJack** [LukeSmithxyz/voidrice#204] opened 2019-01-31 17:00 UTC
I'm having this slightly annoying issue that whenever I boot up the computer and log in, the statusbar displays a message

> Error: status_comand process exited unexpectedly (exit 0)

This issue usually gets resolved as soon as I hit `$mod+F2` to restart i3.
Unfortunately I've been unable to get any further information that would help me to determine what exactly is causing the problem - it could be one of the scripts but again - I don't know since restarting i3 works fine making this more of an annoyance than breaking bug.

**Comment by ZethJack** [comment] 2019-01-31 20:22
Hard to tell. Is there a way to get some kind of log?

**Comment by ZethJack** [comment] 2019-02-01 10:47
Guess I could go into the i3status config and disable all modules, then enable them one by one, rinse and repeat. Now this might take me a while - so I won't get to it any sooner than tomorrow. I'll report back once I have something.

**Comment by LukeSmithxyz** [comment] 2019-02-02 12:36
Closing this as it is a duplicate of LukeSmithxyz/LARBS/issues/90

The solution should be there and involved the `mpdupdate` script. It has been updated in this repo and should be fixed now.

**Closed by LukeSmithxyz** 2019-02-02 12:36 UTC
