### ISSUE TITLE
dmenuunicode help

### ISSUE THREAD

**Issue by flamendless** [LukeSmithxyz/voidrice#136] opened 2018-10-31 10:04 UTC
Hey, really like your youtube channel, i learn a lot of stuffs about linux!

I just want to ask how to properly show unicode with dmenuunicode? When i run the script, it works, but some are missing (only a block), like the hat. 

(I use i3wm, termite on my manjaro if that will help) Thanks!

**Comment by LukeSmithxyz** [comment] 2018-11-01 15:16
Be sure to:
- have a unicode font installed with wide coverage (like `ttf-symbola` from the AUR)
- have `xclip` installed or the copying won't work.

**Comment by flamendless** [comment] 2018-11-02 01:04
Thanks for responding!

It seems that i need the ttf-symbola font, thanks!

**Comment by flamendless** [comment] 2018-11-02 01:52
ive tried pasting it to my terminal and browser, same output. I already installed ttf-emojione and noto-fonts-emoji, still same :/

How come it shows properly on the dmenu bar but the xclip output "copied to clipboard" shows a block only.
(PS. some emoji works though)

**Comment by hepan-git** [comment] 2018-11-03 18:18
>I already installed ttf-emojione and noto-fonts-emoji
Maybe uninstall one of them? It could be because you have both installed as Luke said **or** not **and**.

**Comment by flamendless** [comment] 2018-11-04 00:00
@hepan-git did that. Still the same

_Sent from my Liquid Zest 4G using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by LukeSmithxyz** [comment] 2019-02-19 13:09
I should've added that `noto-fonts` may be required as well since some of the characters are non-emojis.

I think I'm going to close this issue because (a) it isn't really a LARBS issue, but a general dmenu/dwm issue (which you can avoid, but it does happen) and (b) both dmenu/dwm will be removing the cause of this error on the next release.

It does have to do with you not having a character in the required font though. If you have this problem, you'll need a more extensive font package or you can comment out the problematic characters.

**Closed by LukeSmithxyz** 2019-02-19 13:09 UTC
