### ISSUE TITLE
Pulseaudio fails to start for some programs

### ISSUE THREAD

**Issue by rmwalk** [LukeSmithxyz/voidrice#752] opened 2020-07-09 09:00 UTC
I switched from arch to artix yesterday, ran larbs and everything worked fine. But pulseaudio is not working with some programs. I get no audio at all in brave and ungoogled chromium. But I do get audio in firefox and mpv. If I run firefox first, then when I run brave the audio is fine, but if I close both it seems like pulseaudio is killed and when I check on the terminal it says that there's no pulseaudio running. I tried starting it with xinit and got the same result. Starting pulseaudio from the command line works until I close brave. If I do it and run it again, the audio is gone and I get the same "no pulseaudio running" message. And the odd thing is that it only appears to happen in dwm. I installed bspwm, i3 and awesome just to test it and I get audio just fine in brave and ungoogled chromium in those WMs. Maybe it's something to do with runit? Any ideas how to fix it?

**Comment by AlexSyssoyev** [comment] 2020-07-09 12:46
I actually got the same problem with brave. I have to restart it 3 times to get audio on it. I don't know why but i got used to it, it would be cool though if there was a fix for this.

**Comment by dschense** [comment] 2020-07-18 07:23
Same here. Sometimes just getting the "Dummy-output" as Audio-Device in brave. Then I have to kill brave or stop the running Video/Audio, reload it and have my audio-device back. sometimes its working, sometimes not ^^

**Comment by AlexSyssoyev** [comment] 2020-07-18 12:40
Apparently pulseaudio crashes when idle. Couldn't figure out why.

**Comment by rmwalk** [comment] 2020-07-18 21:59
Yep, it's really annoying. I think it might be something to do with runit because I have the same problem on my other machine with void installed.

**Comment by dschense** [comment] 2020-07-23 11:47
Seems this fixed my problem:

The Last Post on the page.
[ALSA unable to find card [SOLVED]](https://bbs.archlinux.org/viewtopic.php?id=255908)

after doing this my sound is working like expected. Dont know if this is the correct way and whats the cause of the problem..
but this seems to work - even on ArtixLinux.

**Comment by rmwalk** [comment] 2020-07-23 15:36
Just tried both methods above and still have the same problem. I don't think it's related to LARBS (as the guy mentioned on his post) because on my void machine I had this exact same issue and I did not run LARBS on it. That's why I think it's some issue with the way runit manages alsa/ pulse and maybe related to our hardware.
This is the kind of thing that drives me nuts because sometimes the audio works, sometimes it doesn't. Sometimes I boot my machine and the audio is working right off the bat, sometimes it takes some effort to get it working. Not being able to rely 100% on it when needed has become a problem to me. Other than that artix has been really great, but this is the kind of thing I cannot live with and I decided to go back to arch, probably will do so next weekend.

**Comment by AlexSyssoyev** [comment] 2020-07-23 15:58
> Just tried both methods above and still have the same problem. I don't think it's related to LARBS (as the guy mentioned on his post) because on my void machine I had this exact same issue and I did not run LARBS on it. That's why I think it's some issue with the way runit manages alsa/ pulse and maybe related to our hardware.
> This is the kind of thing that drives me nuts because sometimes the audio works, sometimes it doesn't. Sometimes I boot my machine and the audio is working right off the bat, sometimes it takes some effort to get it working. Not being able to rely 100% on it when needed has become a problem to me. Other than that artix has been really great, but this is the kind of thing I cannot live with and I decided to go back to arch, probably will do so next weekend.

Hey did you try to take a look at the /tmp/pulse directory? I had this unrelated issue with the display and realized that runit does not cleanup the cache at all. So i wrote [this](https://forum.artixlinux.org/index.php?PHPSESSID=c4v4u9mk31pa92is4r6kbob9ev&topic=886.msg6796#msg6796) in my fstab and the pulse error does not happen that often. It happens from time to time but i just restart brave and it works. It's a long shot but maybe it will help you.

**Comment by rmwalk** [comment] 2020-07-23 17:51
I'll try it when I get home. If a single brave restart solved the issue for good at least for the whole session until I turned off the pc, it wouldn't actually annoy me that much. But even though I use brave more often than firefox, I still use the latter a fair bit of time and when brave audio is working but I play something on FF, it kills the audio for brave. Even the dwmblocks volume doesn't seem to respond. 
Anyway, I'll try your suggest later today. Thanks

**Comment by dschense** [comment] 2020-07-23 21:59
It must be a runit thing. Setup a clean Archlinux and dont have any of these problems. For me its happening when using brave in combination with artixlinux runit.

**Comment by rmwalk** [comment] 2020-07-24 07:42
Well I tried the fstab suggestion and after the first reboot the audio wasn't working. I decided to back up a couple things real quick and just installed arch and ran larbs on it. Like dschense, I don't have any problems with audio in arch, pulse works fine. I'll close this issue now, thanks for the suggestions guys.

**Comment by AlexSyssoyev** [comment] 2020-07-27 17:12
For future references [this](https://rtfm.co.ua/en/linux-alsa-lib-pcm_dmix-c1108snd_pcm_dmix_open-unable-to-open-slave-2/) solved the issue for me. Tried rebooting around 5 times and everything works as it should.

**Comment by AlexSyssoyev** [comment] 2020-10-08 13:11
So i got this issue again and i found out that fluidsynth was the reason behind it. At the end on the troubleshooting part there is the [fix](https://wiki.archlinux.org/index.php/FluidSynth). Removing fluidSynth isn't an option because its a dependency for mpd. 

So i did that and i haven't suffered from this issue anymore. Try it.

**Comment by LukeSmithxyz** [comment] 2020-10-08 14:20
Okay, yeah Alex, that seems to be it. I'm going to include a line in the LARBS script that adds that line to the fluidsynth config. Seems to be working.

**Closed by LukeSmithxyz** 2020-10-08 14:20 UTC
