### ISSUE TITLE
stty standard input error

### ISSUE THREAD

**Issue by kronikpillow** [LukeSmithxyz/voidrice#394] opened 2019-10-24 20:37 UTC
I keep getting `stty: 'standard input': Inappropriate ioctl for device` and I'v been busting my self for over 2 weeks now to figure out what is causing it, after a fresh install its not there, then after some time, after messing with dotfiles like adding your .zshrc, updating some variables, and linking root user dotfiles to main user dotfiles it starts to display this error, have you ever encountered such problem? how do i debug this? 

[edit]
figured out the reason behind it by reinstalling and going step by step of my post install process till i found it ... the reason for this is the 'stty -ixon # Disable ctrl-s and ctrl-q.' in .bashrc, for some reason, when the root users's .bashrc is linked to the main users .bashrc via a symlink or via editing /etc/passwd and changing the root users home directory, it starts displaying this error ... :-/ anyone have an idea how to avoid this without enabling ctrl+s ctrl+q again as both the error and ctrl+s ctrl+q are annoying :dagger:

**Comment by LukeSmithxyz** [comment] 2019-11-24 13:40
I'm going to close this issue since it's not really caused by something directly in the dotfiles. They use zsh nowadays anyway.

**Closed by LukeSmithxyz** 2019-11-24 13:40 UTC
