### ISSUE TITLE
My Font Suddenly Changed

### ISSUE THREAD

**Issue by pondakun** [LukeSmithxyz/voidrice#1033] opened 2021-11-11 11:35 UTC
After ai update p -Syu i have the problem that the status bar was bold and the programs i open wan not in corect resolution. so As newbie - newborn - what ever i format and reinstal Arch linux and larbs.sh and in fresh install i have the same broblem statusbar is too big for 1920x1980 resolution and programs like pcmanfm show to big 
![pic-selected-211111-1636-47](https://user-images.githubusercontent.com/53324347/141291482-d67375b0-6629-4854-91c8-74279b3d6d02.png)

Edit reson more info

**Comment by JC-Morph** [comment] 2021-11-11 15:12
same

**Comment by LukeSmithxyz** [comment] 2021-11-11 15:15
Fixed in 90fa3d5b3be9a4c03150eb76d1dae94076f899f7.

The issue is that some Xorg update affected the default assumed DPI. I will now have it explicitly set to 96, which is typical, although users are advised to check which DPI value works best for their screens.

**Closed by LukeSmithxyz** 2021-11-11 15:15 UTC
