### ISSUE TITLE
i3 configuration does not support intuitive grid navigation

### ISSUE THREAD

**Issue by drobe504** [LukeSmithxyz/voidrice#280] opened 2019-04-19 23:41 UTC
The tree structure i3 uses to model its workspaces is such that left/right/up/down navigation is not intuitive in grids. Whether left/right/up/down works correctly is dependent upon how you split the windows. I have not seen an adequate solution to this elsewhere, but it should be doable. I started looking into this but don't have time at the moment.
Doing `i3-msg -t get_tree | jq -c '.nodes | .[] | .nodes | .[] | .nodes | .[]' | grep -E focused..true` returns the current workspace. Further jq swizzling can be done to:
1) get the current node from the workspace json
2) get the the x/y value of the current node from the current node json
3) get the new node (up -> same x, higher y; down -> same x, lower y; etc...) from the current workspace json
3) call `i3-msg focus` to move to the appropriate node based on that information

I'd be interested in hearing if anyone has already seen an implementation of this elsewhere or if anyone has some other workaround.

**Comment by lhindir** [comment] 2019-04-21 06:55
This [i3-gaps issue](https://github.com/Airblader/i3/issues/258) which I found by searching the issues for “move between windows” shows that it’s by design and there isn’t a simple workaround. A cursory internet search (“i3 move grid layout” “i3 navigate 2x2”) show [similar results](https://reddit.com/r/i3wm/comments/7x375z/any_plans_for_native_grid_layout_support/). Considering this repo is someone’s personal dotfiles (usually installed by beginners with a script), the problem is a little out of scope. It looks like Luke usually just closes issues like these.

Maybe a different window manager could solve your problem? herbstluftwm might do the trick.

**Comment by LukeSmithxyz** [comment] 2019-04-21 11:52
This is not an "issue"; this is the built-in functionality of i3 and intended. i3 has a tree layout. I would say "open this issue on the i3 repository", but what you'd really want is to use another window manager if you want this behavior.

**Closed by LukeSmithxyz** 2019-04-21 11:52 UTC
