### ISSUE TITLE
Refbar isn't refreshing the dwm statusbar

### ISSUE THREAD

**Issue by m160** [LukeSmithxyz/voidrice#386] opened 2019-10-09 23:24 UTC
So it looks like some changes have been made in the scripts since the [status bar](https://open.lbry.com/@Luke:7/customizing-a-status-bar-in-dwm-weather:c) video. Not sure why, but refbar isn't refreshing my status bar with the latest [refbar](https://github.com/LukeSmithxyz/voidrice/blob/voiddwm/.local/bin/refbar) and [dwmbar](https://github.com/LukeSmithxyz/voidrice/blob/voiddwm/.local/bin/dwmbar) scripts.

I'm on Pop!_OS so I haven't done LARBS or anything. If I'm not mistaken that shouldn't matter too much as it's just one script triggering the other, but I'm still a Linux newb. any suggestions?

**Comment by Wayloque** [comment] 2019-10-10 13:32
I'm not sure whether this would work for you. But for me, I changed the [refbar](https://github.com/LukeSmithxyz/voidrice/blob/voiddwm/.local/bin/refbar) scripts from this `pkill -SIGTRAP dwmbar` to this `pkill -SIGTRAP $(dwmbar)` and it works for me on my machine. Hope this helps.

**Comment by m160** [comment] 2019-10-10 14:35
Yeah, that appears to refresh the status bar, I say _appears_ because it looks more like it's just starting a new instance of dwmbar rather than refreshing the current one. If I do something that calls refbar repeatedly, like increasing/decreasing the volume, I'm left with this:
![Screenshot-2019-10-10_15:20:48](https://user-images.githubusercontent.com/34570404/66577715-c4f91200-eb71-11e9-80e6-960893fa571d.png)

**Comment by Wayloque** [comment] 2019-10-11 00:37
Oh, I only realized it now as you mentioned about it. But I did some digging and found out adding `-f` option to the command in [refbar](https://github.com/LukeSmithxyz/voidrice/blob/voiddwm/.local/bin/refbar) script like this `pkill -f -SIGTRAP dwmbar` actually works as intended and won't repeatedly start new dwmbar as in the image you shown. Sorry for the confusion as I'm also a Linux newb that still learning just like you. If this still doesn't work, let me know and I'll try my best to help.

**Comment by m160** [comment] 2019-10-12 01:31
Nice one! It's a bit slow, like if I increase the volume, it's reflected in the status bar half a second later, but definitely a huge improvement!

I assume the delay is cause by the fact that the whole status function is updated rather than just the little volume section within it. If I split the big status function that includes everything into separate functions for each thing, would I be able to refresh them independently?

**Comment by Wayloque** [comment] 2019-10-12 04:40
For me, I don't experience any delay. The status refresh immediately as I pressed increase volume button.

As far as I know, separating the functions and refreshing them independently seem impossible at least for me.

**Comment by m160** [comment] 2019-10-12 11:09
My bad. I had added something that had a 0.5 sleep in it, causing the delay.
Now it refreshes instantly. Thanks for the help :)

**Comment by Wayloque** [comment] 2019-10-12 13:38
Welcome. Happy to help :)

**Comment by LukeSmithxyz** [comment] 2019-11-23 12:58
Closing this as `refbar` has been removed and replaced by my `dwmblocks` build.

**Closed by LukeSmithxyz** 2019-11-23 12:58 UTC
