### ISSUE TITLE
Dmenurecord no default input device issue

### ISSUE THREAD

**Issue by slavan128** [LukeSmithxyz/voidrice#641] opened 2020-05-17 13:52 UTC
Hello comunity,

I realised I canno't get my screencast on LARBS to work

I tryed install arch on 4 devices (ThinkPad X200, X220, X230, VM, X220 with manjaro, i3 nor DWM same issue), every time exactly same issue

I tryed to set my ".asoundrc", but nothink works

- video recording works without any issue
- audio is also not working

- on LARBS from october/nevember 2019 everythink worked, until I decided to upgrade to newer manjaro on april (a 2 days ago again)

- i'm thinkinking why it cannot work (on new larbs were made some changes with minilaizing home directory file count)

output of terminal screencast

```
[x11grab @ 0x5590f4bee940] Stream #0: not enough frames to estimate rate; consider increasing probesize
Input #0, x11grab, from ':0':
  Duration: N/A, start: 1589723083.990644, bitrate: N/A
    Stream #0:0: Video: rawvideo (BGR[0] / 0x524742), bgr0, 2560x1024, 60 fps, 1000k tbr, 1000k tbn, 1000k tbc
ALSA lib pcm_hw.c:1829:(_snd_pcm_hw_open) Invalid value for card
[alsa @ 0x5590f4bf8600] cannot open audio device default (No such device)
default: Input/output error
```
output of terminal - audio

```
[alsa @ 0x55c936118640] cannot open audio device default (No such device)
default: Input/output error
```

Have a nice day ;)

**Comment by AlexSyssoyev** [comment] 2020-05-17 17:27
If you have this problem specifically with Arch you should try to make a post in the [arch linux forum](https://bbs.archlinux.org/index.php). There they will be able to help you better than we can. Maybe you will get lucky and someone here might know about the subject but personally i think audio settings are the least documented and more troublesome theme on linux.

**Comment by peterrisa** [comment] 2020-05-17 17:31
It is definitely with LARBS, because if I use my old archived dotfiles, it still work on same installation.

Thank you!

**Comment by slavan128** [comment] 2020-05-17 17:36
Thank you, but it is definitely with LARBS, because I tested this also. I copyed my old dotfiles (and also some archived version of LARBS for testing and it worked)

- this issue appeard in months between december 2019 and end of march 2020 - until now

Thank you for your time ;)

**Comment by AlexSyssoyev** [comment] 2020-05-17 17:51
Its probably because of the change from alsa to pulseaudio that happened on april. If you switch to alsa you will probably get it back as it was before.

**Comment by slavan128** [comment] 2020-05-17 17:55
I've tried every setting (pulse and alsa was first about what I thought) - it doesn 't worked

That is why I made this post, because I hate OSB and I must record videos often

**Comment by LukeSmithxyz** [comment] 2020-05-18 20:52
The most recent dotfiles do use pulseaudio. The record commands, however shouldn't've changed.

The issue is likely your default audio input is unclear since pulse is now being used and it may not have the default your want. I'd open up `pulsemixer` and check to see what your default input (`F2`) is and set it to what you want. It's very possible that it might be some dummy input by default until you change it.

**Comment by msahores** [comment] 2020-05-20 14:35
Here I'm having the exact same error after pulling the lasts from the repo a few days ago.

**Comment by 26-55-87-BuddhiLW** [comment] 2020-05-21 21:09
Me too. I'm having this problem, and I went to Archforum. But, we should do use a personalized-build for our own count and risk. I believe I was borrowing a great deal of time and energy from a moderator, V1del, and It would not aggregate for the arch community in general 

Anyhow, if I pull the latest larbs build, I have no audio problem, because `asound -l` recognizes the hardwares as before. But, X11 won't load properly, accusing it can't find some Xfiles.

Move .config/ files to another place. And, rebuild, by the script. If it works, great.

(Caution, you will have to use root-user, if the X11 does not load for the conventional one. Be sure to remember the password etc or you will get stuck)

**Comment by LukeSmithxyz** [comment] 2020-05-21 22:57
Closing this. Again, this is not an issue with any dotfiles here, but with your default pulseaudio settings. Choose/hook up a valid input device as default and you will not get this error.

**Closed by LukeSmithxyz** 2020-05-21 22:57 UTC

**Comment by 26-55-87-BuddhiLW** [comment] 2020-05-25 07:47
I would not like to give any troubles, and re-open for no reason, but I find it valid to share what I did to personally solve the issue. 

You are right, 

> (...)this is not an issue with any dotfiles here, but with your default pulseaudio settings. Choose/hook up a valid input device as default and you will not get this error.

But that does not give a straight solution to the problem, won't we agree?

Anyhow, here is the [https://bbs.archlinux.org/viewtopic.php?id=255908](thread) I used in archlinux's forum, in case anyone, in the future, have the same issue.

Basically, remove all sound config related files (if not precious to you in any particular way; in that case, move them), including alsa and pulse itself. And, reinstall them with pacman -Sy. Because, you won't be able to simply use something like alsactl that supposedly would handle this situation - once asound.state is generated alsa makes sure to lock it, there are workaround's it, but they all defeat the purpouse and I could not make them work.

**Comment by slavan128** [comment] 2020-05-25 10:21
Yeah, I have done this also in past, it won't helped. (about month ago)
![image](https://user-images.githubusercontent.com/65496058/82804165-1ac0c700-9e82-11ea-9c82-4a1bb800b0ce.png)

**Comment by 26-55-87-BuddhiLW** [comment] 2020-05-25 13:32
Is your sudo asound -l, and normal-user asound -l outputs different?

In that case, have you tried using sudo su, and trying to record?

**Comment by slavan128** [comment] 2020-05-25 13:36
Thank you, you soved everythink
![image](https://user-images.githubusercontent.com/65496058/82817577-83696d00-9e9d-11ea-8e6d-3002bd2d3f90.png)

**Comment by V1del** [comment] 2020-05-25 14:09
@LukeSmithxyz 

We are talking ALSA commands and utilities here, pulseaudio doesn't matter when aplay -l fails.

What do you think happens with a ~/.profile: of 

https://github.com/LukeSmithxyz/voidrice/blob/master/.zprofile#L28

leading to a file of

https://github.com/LukeSmithxyz/voidrice/blob/master/.config/alsa/asoundrc

on systems where the assumptions in that file don't hold true?

All of the above. 

If this is in any way intended to be used by anyone other than yourself you really shouldn't override ALSA_CONF_DIR without good reason, if you want to enforce a custom .asoundrc (though you definitely shouldn't do that either unless it's something that can have global relevance, like shipping a config that redirects to pulse instead of hardcoded devices)

**Comment by LordRusk** [comment] 2025-03-22 18:39
I had to log back into an account i havent logged into for a long time.

No, @LukeSmithxyz, if LARBS uses pulse, then you should change the script to use pulse. Is there something i am missing here? if not, then @V1del should not be saying "probably".

I don't use larbs, but years back I did, and i've kept this script in my dotfiles. Using alsa while the system is configured with pulse audio is maddness.

**Comment by V1del** [comment] 2025-03-23 16:25
I'm fairly certain most of this got fixed eventually and AFAIK the current files don't have this particular issue anymore. But I also don't use LARBS, but this definitely was a bug that broke an Arch users audio which is the only reason I even became aware of the issue. 

I used "probably", because technically the relevant ffmpeg commands can keep using alsa if the ALSA default device is appropriately redirected to a pulseaudio/pipewire server. Since ffmpeg supports pulse natively it'd probably give you better synchronisation and latency guarantees but it shouldn't flat out not work, like was the case with the originally incorrect configuration. 

That said you're 4 years late, chances that this changed by now are somewhat present.
